# Generated by Django 5.1 on 2025-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accutrack_app', '0003_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
