# Generated by Django 5.1 on 2025-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accutrack_app', '0005_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='position',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
        ),
    ]
