# Generated by Django 5.1 on 2025-01-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accutrack_app', '0007_remove_service_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
